repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: examples/picking/_rollout_generator.py
- repo: https://github.com/openstack/hacking
  rev: 4.1.0
  hooks:
  - id: hacking
    exclude: examples/picking/_rollout_generator.py
